create table LOAN_PAYMENT
(
	ID INTEGER not null
		primary key,
	DATE TIMESTAMP,
	SUM_PAYMENT DOUBLE,
	SUM_PAYMENT_LOAN DOUBLE,
	SUM_PAYMENT_PERCENTS DOUBLE,
	LOAN_OFFER_ID INTEGER
		constraint FKM5P0OL3N292XMWNWIK4AYISTS
			references LOAN_OFFER
);

